[project]
dependencies = [
  "langgraph>=0.6.8",
  "langgraph-checkpoint-sqlite>=2.0.11",
  "python-dotenv>=1.1.1",
  "trustcall>=0.0.39",
  "wikipedia>=1.4.0",
]
description = "Add your description here"
name = "foundation-introduction-to-langgraph"
readme = "README.md"
requires-python = ">=3.12"
version = "0.1.0"

[dependency-groups]
dev = [
  "ipykernel (>=6.30.1,<7.0.0)",
]
